version: build{build}

image: Visual Studio 2022
configuration: Release

branches:
  only:
    - master

build_script:
  - cmake -S . -B build -G "Visual Studio 17 2022" -A x64
  - cmake --build build --config Release

artifacts:
  - path: build\Release\stuntcarracer.exe

deploy:
  skip_tags: true
  description: Windows build
  provider: GitHub
  auth_token:
    secure: M9xvUw78oWu2qIEvVQ7bYKIfSrIDO4twEjWq3yaR8JVKcI4uUPAMfJuITLI+AfCS
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
